<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Play Video_vjs-icon-placeholder</name>
   <tag></tag>
   <elementGuidId>b4ad2076-7ca6-479c-afc5-d80070f4958d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.vjs-play-control.vjs-control.vjs-button.vjs-playing > span.vjs-icon-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='example-video']/div[4]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d85f0538-fb5c-45f1-acc9-43e94146c5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>251a14af-0ecd-48b7-a6a1-a22c587238fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-icon-placeholder</value>
      <webElementGuid>81befc61-e0b7-4716-a246-94d696d59af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example-video&quot;)/div[@class=&quot;vjs-control-bar&quot;]/button[@class=&quot;vjs-play-control vjs-control vjs-button vjs-playing&quot;]/span[@class=&quot;vjs-icon-placeholder&quot;]</value>
      <webElementGuid>426c9a7f-304b-40ea-989b-de8b4d488d91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='example-video']/div[4]/button/span</value>
      <webElementGuid>d54ab1aa-22c9-4795-a634-c3230133205c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/span</value>
      <webElementGuid>4db801dc-7b67-4e32-a6f1-0ed9a816e00a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
